---
nginx_user: vagrant
nginx_port: 80
nginx_port_tls: 443
nginx_server_name: localhost

php_memory_limit: 1024M
php_is_develop: True

wordpress_version: 4.8.3
wordpress_sha256sum: 42ca594afc709cbef8528a6096f5a1efe96dcf3164e7ce321e87d57ae015cc82

wordpress_db_name: wordpress
wordpress_db_user: wordpress
wordpress_db_password:

