---
- include: centos.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version >= 6

- name: Upload nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: Restart nginx

- name: Upload default.conf
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify:
    - Restart nginx
    - Restart php-fpm
